users:
  admin:
    username: admin
    password_hash: 36c8119529af3de632d7ec878e26324a:5bdc69b025447a57ae30f13fe32c6637b5140337525c81a8d82f1bf0e56bb662
    role: admin
    email: null
    full_name: Default Administrator
    is_active: true
    created_at: '2026-02-25T03:02:14.527772+00:00'
    last_login: '2026-03-01T14:57:19.319470+00:00'
    last_password_change: '2026-02-25T03:02:14.527780+00:00'
  test:
    username: test
    password_hash: 32a34938ddb94d287e57cb55e299b87e:ab0a5554d3571f6fcf9520461bea5cf45a06329d2e31f9f0aafe428fe2a060a0
    role: viewer
    email: testuser@gmail.com
    full_name: test user
    is_active: true
    created_at: '2026-02-25T03:12:33.671894+00:00'
    last_login: '2026-02-25T03:36:42.583397+00:00'
    last_password_change: '2026-02-25T03:12:33.671896+00:00'
last_updated: '2026-03-01T14:57:19.319522+00:00'
